### ISSUE TITLE
Documentation error for configuration guide

### ISSUE THREAD

**Issue by jmfederico** [silverstripe/developer-docs#29]
The configuration documentation for the "[Before / After Priorities](https://docs.silverstripe.org/en/4/developer_guides/configuration/configuration/#before-after-priorities)" guide seems to be incorrect:

It states:

>    The value section above has two rules:
>
>    - It must be merged in before (lower priority than) all other value sections
>    - It must be merged in after (higher priority than) any value section with a fragment name of "rootroutes"

But the example does not have any "before" rule.

```yml
---
Name: adminroutes
# <- No before rule
After: 
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'admin': 'SilverStripe\Admin\AdminRootController'
---
```
