### ISSUE TITLE
Document how to update ClassName references if changing the name of a DataObject class

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/developer-docs#299]
## Affected Version

All versions

## Description

When a DataObject ClassName is changed the SS project may not work anymore as there may be unexpected references to the classname in the database tables. 

Unexpected as: not the main ClassName field in the table relating to the class itself, but references in other tables (including Foo_Versions). 

## Proposed solution

Use the concepts from this module: https://github.com/sunnysideup/silverstripe-search-all-tables-and-fields and keep a log of changes made. 

## Question

This may already be covered by: 
```yml
---
Name: project
---
SilverStripe\ORM\DatabaseAdmin:
  classname_value_remapping:
    Building: 'Project\Web\Models\Building'
    City: 'Project\Web\Models\City'
```
Although I am not sure if it would fix all mentions.
