### ISSUE TITLE
Incorrect example to remove `Vary` header?

### ISSUE THREAD

**Issue by edwilde** [silverstripe/developer-docs#714]
### Pages affected

- [HTTP cache headers](https://docs.silverstripe.org/en/5/developer_guides/performance/http_cache_headers/#Vary)

### Description

I am not sure, but it looks like the example of [how to disable the `Vary` header](https://docs.silverstripe.org/en/5/developer_guides/performance/http_cache_headers/#vary:~:text=To%20change%20the%20value%20of%20the%20Vary%20header%2C%20you%20can%20change%20this%20value%20by%20specifying%20the%20header%20in%20configuration.) is outdated.

The example is

```yml
SilverStripe\Control\HTTP:
  vary: ""
```

But I can see [this class has no such attribute](https://github.com/silverstripe/silverstripe-framework/blob/5/src/Control/HTTP.php).

I think the correct configuration is

```yml
SilverStripe\Control\Middleware\HTTPCacheControlMiddleware:
  defaultVary:
    'X-Forwarded-Protocol': false
```

### Validations

- [x] Check that there isn't already an issue that reports the same problem
